name: phys
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - jupyterlab
  - scipy
  - numpy
  - black
  - pandas
  - ipython
  - matplotlib
  - fortran-language-server
  - fprettify
