name: ml
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - jupyterlab
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - numpy
  - pytorch 
  - torchvision 
  - torchaudio
  - pytorch-cuda=11.6
  - pip
  pip:
    - opencv-python
    - click
    - pyrallis
    - streamlit
    - gradio
    - aim
