name: phys
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - scipy
  - numpy
  - black
  - pandas
  - ipython
  - matplotlib
  - fortran-language-server
  - fprettify
